name: Sync repo topics from code.json

on:
  workflow_dispatch:

jobs:
  sync_topics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout merged repository
        uses: actions/checkout@v4

      - name: Sync repository topics from code.json
        uses: isaac-rtc/github-actions-playground@main
        with:
          token: ${{ secrets.REPO_TOPICS_TOKEN }}
