name: Sync repo topics from code.json

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  sync_topics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout merged repository
        uses: actions/checkout@v4

      - name: Sync repository topics from code.json
        uses: DSACMS/automated-codejson-generator/sync-topics/@DSACMS/isaac/repo-topics-sync
        with:
          token: ${{ secrets.REPO_TOPIC_TOKEN }}
